// R-WORKFLOW-CHAIN-V1 — public surface for workflow chain module.
// Legacy conversational workflow types (WorkflowStep, WorkflowStepKind, etc.)
// are NOT re-exported here. Import them directly from ./types.ts to keep the
// two systems visually distinct at call sites.

export * as WorkflowChainTypes from './workflowChainTypes';

export type {
  WorkflowChainStatus,
  WorkflowChainStepStatus,
  WorkflowChainStepKind,
  WorkflowChainStep,
  WorkflowChain,
  WorkflowContinuationKind,
  WorkflowContinuation,
  WorkflowReadinessResult,
  WorkflowTransitionReason,
  WorkflowTransition,
  WorkflowDependencyKind,
  WorkflowDependency,
  WorkflowGraphReadinessResult,
  WorkflowExecutionCandidatesResult,
  WorkflowPlanMode,
  WorkflowPlanItem,
  WorkflowPlanResult,
  WorkflowExecutionDecisionState,
  WorkflowExecutionDecisionReason,
  WorkflowExecutionDecision,
  WorkflowExecutionDecisionResult,
  WorkflowPolicyEvaluationState,
  WorkflowPolicyEvaluationReason,
  WorkflowPolicyEvaluation,
  WorkflowPolicyEvaluationResult,
  WorkflowOrchestrationIntentState,
  WorkflowOrchestrationIntentReason,
  WorkflowOrchestrationIntent,
  WorkflowOrchestrationIntentResult,
  WorkflowRuntimeCapabilityKind,
  WorkflowRuntimeCapabilityState,
  WorkflowRuntimeCapability,
  WorkflowRuntimeCapabilityResult,
  WorkflowExecutionContractRequirement,
  WorkflowExecutionContractState,
  WorkflowExecutionContract,
  WorkflowExecutionContractResult,
  WorkflowRuntimeAuthority,
  WorkflowRuntimeLifecycleState,
  WorkflowRuntimeBoundary,
  WorkflowRuntimeBoundaryResult,
  WorkflowExecutionSessionScope,
  WorkflowExecutionSessionState,
  WorkflowExecutionSessionIdentity,
  WorkflowExecutionSessionIdentityResult,
  WorkflowRuntimeOwnerKind,
  WorkflowRuntimeOwnershipState,
  WorkflowRuntimeOwnership,
  WorkflowRuntimeOwnershipResult,
  WorkflowAuthorityActorKind,
  WorkflowAuthorityResolutionState,
  WorkflowAuthorityRequirement,
  WorkflowAuthorityResolution,
  WorkflowAuthorityResolutionResult,
  WorkflowAuthorityDelegationKind,
  WorkflowAuthorityDelegationState,
  WorkflowAuthorityDelegation,
  WorkflowAuthorityDelegationResult,
} from './workflowChainTypes';
export {
  createWorkflowChain,
  createWorkflowChainStep,
  getWorkflowChains,
  getWorkflowChain,
  addWorkflowChainStep,
  updateWorkflowChainStepStatus,
  clearWorkflowChains,
  createWorkflowChainFromApproval,
  syncWorkflowStepFromApproval,
  createWorkflowTransition,
  getWorkflowTransitions,
  clearWorkflowTransitions,
  createWorkflowContinuation,
  getWorkflowContinuations,
  clearWorkflowContinuations,
  evaluateWorkflowReadiness,
  evaluateWorkflowGraphReadiness,
  evaluateWorkflowExecutionCandidates,
  evaluateWorkflowPlan,
  evaluateWorkflowExecutionDecisions,
  evaluateWorkflowPolicies,
  evaluateWorkflowOrchestrationIntent,
  evaluateWorkflowRuntimeCapabilities,
  evaluateWorkflowExecutionContracts,
  evaluateWorkflowRuntimeBoundary,
  evaluateWorkflowExecutionSessionIdentity,
  evaluateWorkflowRuntimeOwnership,
  evaluateWorkflowAuthorityResolution,
  evaluateWorkflowAuthorityDelegation,
  createWorkflowDependency,
  getWorkflowDependencies,
  clearWorkflowDependencies,
  evaluateWorkflowDependencyState,
} from './workflowChain';
